# Generated by Django 3.2.16 on 2023-02-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('produto_favorito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_nat',
            fields=[
                ('clientes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.clientes')),
            ],
            bases=('clientes.clientes',),
        ),
    ]
