# Generated by Django 3.2.16 on 2023-02-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto_favorito', '0002_email_nat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email_nat',
        ),
    ]
