# Generated by Django 3.2.16 on 2023-02-08 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('produto_favorito', '0003_delete_email_nat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('email', 'produto')},
        ),
    ]
